embedding_size: 64
feat_embed_dim: 64
cf_model: lightgcn

use_knn: True
knn_k: 10
n_knn_layers: 1

alpha: 0.1

tau: 0.2


hyper_parameters: ["n_ui_layers", "n_vc_layers", "n_tc_layers", "beta", "lamda", "gamma", "drop_rate"]
