# Common Features
USER_ID_FIELD: userID
ITEM_ID_FIELD: itemID
#RATING_FIELD: rating
TIME_FIELD: timestamp

filter_out_cod_start_users: True

inter_file_name: 'baby.inter'

# name of features
vision_feature_file: 'image_feat.npy'
text_feature_file: 'text_feat.npy'

field_separator: "\t"

# n_ui_layers: [1, 2, 3, 4]
n_ui_layers: [2]

n_vc_layers: [2]

n_tc_layers: [3]

drop_rate: [0.5]

gamma: [0.5]

beta: [0.001]  # the weight of contrastive learning

lamda: [100]  # the weight of KL divergence constraint


