# Common Features
USER_ID_FIELD: userID
ITEM_ID_FIELD: itemID
#RATING_FIELD: rating
TIME_FIELD: timestamp

filter_out_cod_start_users: True

inter_file_name: 'clothing.inter'

# name of features
vision_feature_file: 'image_feat.npy'
text_feature_file: 'text_feat.npy'


field_separator: "\t"

n_ui_layers: [2]

n_vc_layers: [3]

n_tc_layers: [3]

drop_rate: [0.7]

gamma: [1.0]

beta: [0.0001]   # the weight of contrastive learning

lamda: [100]  # the weight of KL divergence constraint

