# Common Features
USER_ID_FIELD: userID
ITEM_ID_FIELD: itemID
#RATING_FIELD: rating
TIME_FIELD: timestamp

filter_out_cod_start_users: True

inter_file_name: 'sports.inter'

# name of features
vision_feature_file: 'image_feat.npy'
text_feature_file: 'text_feat.npy'

field_separator: "\t"

# n_ui_layers: [1, 2, 3, 4]
n_ui_layers: [2]
# n_mm_layers: [0, 1, 2, 3, 4]
n_vc_layers: [2]

n_tc_layers: [4]

drop_rate: [0.7]

gamma: [0.5]
# cl_weight : [0.0, 1e-06, 1e-05, 1e-04, 1e-03, 1e-02, 0.1]
beta: [0.001]

lamda: [10000]
# reg_weight : [0.0, 1e-06, 1e-05, 1e-04, 1e-03, 1e-02, 0.1]
#reg_weight: [1e-06]